version: 2
sources:
  - name: DBT_RAW
    database: assessment-project-471715
    schema: DBT_RAW
    tables:
      - name: v_questions
      - name: v_answers
      - name: v_users
      - name: v_tags
      - name: v_question_tag
